### ISSUE TITLE
terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by fallen** [daveshah1/nextpnr-xilinx#12]
After your fix for #4 I did the following:

$ git pull
$ git submodule update --init --recursive
$ cmake -DARCH=xilinx .
$ make -j8

Then:
```

(gdb) run
Starting program: /home/fallen/dev/nextpnr-xilinx/nextpnr-xilinx --chipdb ../../xc7a35t.bin --xdc arty.xdc --json top.json --write top_routed.json --fasm top.fasm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff61b8801 in __GI_abort () at abort.c:79
#2  0x00007ffff6dda957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6de0ab6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6de0af1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6de0d24 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6ddc809 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000555555633bf2 in std::vector<nextpnr_xilinx::CellInfo*, std::allocator<nextpnr_xilinx::CellInfo*> >::_M_check_len (
    __s=0x5555556c0086 "vector::_M_default_append", __n=18446744073708678872, this=0x555555a13fe0) at /usr/include/c++/7/bits/stl_vector.h:1505
#8  std::vector<nextpnr_xilinx::CellInfo*, std::allocator<nextpnr_xilinx::CellInfo*> >::_M_default_append (this=0x555555a13fe0, __n=18446744073708678872)
    at /usr/include/c++/7/bits/vector.tcc:568
#9  0x000055555562cba8 in std::vector<nextpnr_xilinx::CellInfo*, std::allocator<nextpnr_xilinx::CellInfo*> >::resize (__new_size=<optimized out>, this=<optimized out>)
    at /usr/include/c++/7/bits/stl_vector.h:692
#10 nextpnr_xilinx::Arch::Arch (this=0x55555b1d5b30, args=...) at /home/fallen/dev/nextpnr-xilinx/xilinx/arch.cc:84
#11 0x000055555565c9a2 in nextpnr_xilinx::Context::Context (args=..., this=0x55555b1d5b30) at /home/fallen/dev/nextpnr-xilinx/common/nextpnr.h:796
#12 UspCommandHandler::createContext (this=<optimized out>, values=...) at /home/fallen/dev/nextpnr-xilinx/xilinx/main.cc:69
#13 0x00005555555a7b2a in nextpnr_xilinx::CommandHandler::exec (this=0x7fffffffdaf0) at /home/fallen/dev/nextpnr-xilinx/common/command.cc:381
#14 0x000055555559b854 in main (argc=<optimized out>, argv=<optimized out>) at /home/fallen/dev/nextpnr-xilinx/xilinx/main.cc:88

```

I am using the same exact input files as for #4 
Any idea?
Thanks!

**Comment by fallen** [comment]
Seems to work better if I re-generate xc7a35t.bin

**Comment by fallen** [comment]
place and route went OK! thanks and sorry for the noise!

**Comment by fallen** [comment]
I don't know how to produce the .bit file now though
