### ISSUE TITLE
bbaexport.jar compile failed!

### ISSUE THREAD

**Issue by the-centry** [daveshah1/nextpnr-xilinx#37]
xilinx/java/bbaexport.java:802: error: incompatible types: Design cannot be converted to Device
        TimingModel tmg = new TimingModel(des);
                                          ^
xilinx/java/bbaexport.java:996: error: incompatible types: Set<TileTypeEnum> cannot be converted to HashSet<TileTypeEnum>
        HashSet<TileTypeEnum> intTileTypes = Utils.getIntTileTypes();
                                                                  ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/timing/TimingModel.java:800: warning: [removal] Float(float) in Float has been deprecated and marked for removal
        res.put("CKEN1",new Float(SITEPIN_CKEN1_DELAY).shortValue());
                        ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/timing/TimingModel.java:801: warning: [removal] Float(float) in Float has been deprecated and marked for removal
        res.put("CKEN2",new Float(SITEPIN_CKEN2_DELAY).shortValue());
                        ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/timing/TimingModel.java:802: warning: [removal] Float(float) in Float has been deprecated and marked for removal
        res.put("CKEN3",new Float(SITEPIN_CKEN3_DELAY).shortValue());
                        ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/timing/TimingModel.java:803: warning: [removal] Float(float) in Float has been deprecated and marked for removal
        res.put("CKEN4",new Float(SITEPIN_CKEN4_DELAY).shortValue());
                        ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/timing/TimingModel.java:804: warning: [removal] Float(float) in Float has been deprecated and marked for removal
        res.put("SRST1",new Float(SITEPIN_SRST1_DELAY).shortValue());
                        ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/timing/TimingModel.java:805: warning: [removal] Float(float) in Float has been deprecated and marked for removal
        res.put("SRST2",new Float(SITEPIN_SRST2_DELAY).shortValue());
                        ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/timing/TimingModel.java:806: warning: [removal] Float(float) in Float has been deprecated and marked for removal
        res.put("WCKEN",new Float(SITEPIN_WCKEN_DELAY).shortValue());
                        ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/edif/EDIFCellInst.java:99: warning: [dep-ann] deprecated item is not annotated with @Deprecated
    public Map<String, EDIFPortInst> getPortInstMap(){
                                     ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/edif/EDIFNet.java:138: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public Map<String, EDIFPortInst> getPortInstMap(){
	                                 ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/edif/EDIFNet.java:184: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public EDIFPortInst getPortInst(String fullName) {
	                    ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/edif/EDIFNet.java:220: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public EDIFPortInst removePortInst(String portInstName) {
	                    ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/edif/EDIFNetlist.java:1499: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public HashMap<String,EDIFPort> generateEDIFPortMap(){
	                                ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/design/ModuleInst.java:150: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public ArrayList<SiteInst> getInsts(){
	                           ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/util/FileTools.java:1040: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static boolean checkIfRapidWrightResourceExists(String name) {
	                      ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/util/FileTools.java:1751: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static boolean folderCheck(String name){
	                      ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/util/MessageGenerator.java:63: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static void briefErrorAndExit(String msg){
	                   ^
/root/Desktop/project/RapidWright/src/com/xilinx/rapidwright/util/MessageGenerator.java:83: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static void briefMessageAndExit(String msg){
	                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors
17 warnings
CMakeFiles/rapidwright_bbaexport.dir/build.make:82: recipe for target 'CMakeFiles/rapidwright_bbaexport.dir/java_compiled_rapidwright_bbaexport' failed
make[2]: *** [CMakeFiles/rapidwright_bbaexport.dir/java_compiled_rapidwright_bbaexport] Error 1
CMakeFiles/Makefile2:191: recipe for target 'CMakeFiles/rapidwright_bbaexport.dir/all' failed
make[1]: *** [CMakeFiles/rapidwright_bbaexport.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by the-centry** [comment]
A new problem:
"
java -jar rapidwright_bbaexport.jar xczu2cg-sbva484-1-e ../xilinx/constids.inc ../xilinx/xczu2cg.bba
Loading device from file xczu2cg-sbva484-1-e
Exception in thread "main" java.lang.NoClassDefFoundError: com/xilinx/rapidwright/device/IOBankType
	at com.xilinx.rapidwright.device.IOBank.b(Unknown Source)
	at com.xilinx.rapidwright.device.Device.a(Unknown Source)
	at com.xilinx.rapidwright.device.Device.getDevice(Unknown Source)
	at com.xilinx.rapidwright.device.Device.getDevice(Unknown Source)
	at com.xilinx.rapidwright.design.Design.setPartName(Unknown Source)
	at com.xilinx.rapidwright.design.Design.<init>(Unknown Source)
	at dev.fpga.rapidwright.bbaexport.main(bbaexport.java:784)
Caused by: java.lang.ClassNotFoundException: com.xilinx.rapidwright.device.IOBankType
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 7 more
"
